# Generated by Django 2.2.7 on 2019-11-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('daysOfWeek', models.CharField(max_length=100)),
                ('rideInGroup', models.CharField(max_length=100)),
                ('posts', models.IntegerField(blank=True, null=True)),
                ('albums', models.IntegerField(blank=True, null=True)),
                ('photos', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
